env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - sort-exports
  - import
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi: off
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-expect-error:
        descriptionFormat: '^: TS\d+ because .+$'
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
      newlines-between: always
  sort-exports/sort-exports:
    - error
    - sortDir: asc
      ignoreCase: false
      sortExportKindFirst: type
  "@typescript-eslint/sort-type-constituents": error
  "@typescript-eslint/consistent-type-imports":
    - error
    - prefer: type-imports
