name: Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: "${{ secrets.AUTH_TOKEN }}"
          project-id: "${{ secrets.PROJECT_ID }}"
